import angular from 'angular';
import 'angular-ui-router';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';


// Import our templates file (generated by Webpack)
// import './config/app.templates';

import '../style/app.css';

const MODULE_NAME = 'app';

// Import our app functionaity
import './layout';
import './components';
import './home';
import './profile';
import './article';
import './services';
import './auth';
import './settings';
import './editor';

// Create and bootstrap application
const requires = [
  'ui.router',
  //'templates',
  'app.layout',
  'app.components',
  'app.home',
  'app.profile',
  'app.article',
  'app.services',
  'app.auth',
  'app.settings',
  'app.editor'
];

angular.module(MODULE_NAME, requires);

// Mount on window for testing
// window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);
angular.module('app').config(appConfig);
angular.module('app').run(appRun);

export default MODULE_NAME;

// angular.bootstrap(document, ['app'], {
//   // strictDi: true
// });
